apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: builder
spec:
  containers:
    - name: rust
      image: docker.ultimaengineering.io/rust_tarpaulin_builder:latest
      command:
        - cat
      tty: true